nfdi4plants/ARCtrl

src/ISADotnet/JsonExtensions.fs

fixes #22 
Json `AnyOf` deserializer failed when multiple objects where in a list. This is because the commas did not get inserted between objects by the json detokenizer

Fix missing commas in json deserializer

---

src/ISADotnet/API/Person.fs

Fix Person.removeByFullName error

---

RELEASE_NOTES.md
src/ISADotNet.XLSX/AssayFile/Assay.fs
src/ISADotNet.XLSX/ISADotNet.XLSX.fsproj
src/ISADotNet.XLSX/InvestigationFile/Investigation.fs
src/ISADotnet/ISADotNet.fsproj
src/ISADotnet/JsonIO/Assay.fs
src/ISADotnet/JsonIO/Comment.fs
src/ISADotnet/JsonIO/Data.fs
src/ISADotnet/JsonIO/Factor.fs
src/ISADotnet/JsonIO/Investigation.fs
src/ISADotnet/JsonIO/Material.fs
src/ISADotnet/JsonIO/Ontology.fs
src/ISADotnet/JsonIO/Person.fs
src/ISADotnet/JsonIO/Process.fs
src/ISADotnet/JsonIO/Protocol.fs
src/ISADotnet/JsonIO/Publication.fs
src/ISADotnet/JsonIO/Study.fs

- add json io function
- allow reading  and writing xlsx files from a stream

Improve IO functionality

---

src/ISADotNet.XLSX/AssayFile/AnnotationColumn.fs
src/ISADotNet.XLSX/AssayFile/AnnotationNode.fs
src/ISADotNet.XLSX/AssayFile/AnnotationTable.fs
src/ISADotNet.XLSX/CollectionAux.fs
src/ISADotnet/JsonIO/AssayCommonAPI.fs
tests/ISADotNet.Tests/ISADotNet.XLSX/AssayFileTests.fs

Fix issues #34 and #35

---

src/ISADotNet.XLSX/AssayFile/Assay.fs
src/ISADotNet.XLSX/AssayFile/MetaData.fs

Usage:
```fsharp
open ISADotNet
open FSharpSpreadsheetML
open ISADotNet.XLSX.AssayFile
let filePath = @"C:\Users\HLWei\Downloads\TestAssaay.xlsx"
let a = ISADotNet.XLSX.Assays.fromString "LOL" "LEL" "LAL" "LOL" "LEL" "LAL" "LOL" "LEL" []
let p1 = ISADotNet.XLSX.Contacts.fromString "LOL" "LEL" "LAL" "LOL" "LEL" "LAL" "LOL" "LEL" "LAL" "LOL" "LEL" []
let p2 = ISADotNet.XLSX.Contacts.fromString "LEL" "LOL" "LAL" "LOL" "LEL" "LAL" "LOL" "LEL" "LAL" "LOL" "LEL" []
Assay.init "Investigation" (Some a) (Some [p1;p2]) "BestAssay" filePath 
let doc = Spreadsheet.fromFile filePath  true
let p = MetaData.getPersons "Investigation" doc
MetaData.overwriteWithPersons "Investigation" (List.append [p1;p1] p) doc
MetaData.overwriteWithAssayInfo "Investigation" Assay.empty doc
Spreadsheet.close doc
```

Add assay file metadata manipulation capabilities

---

src/ISADotNet.XLSX/AssayFile/AnnotationNode.fs
src/ISADotNet.XLSX/AssayFile/AnnotationTable.fs
src/ISADotNet.XLSX/AssayFile/Assay.fs
src/ISADotNet.XLSX/CollectionAux.fs
src/ISADotNet.XLSX/ISADotNet.XLSX.fsproj
src/ISADotnet/QueryModel/Value.fs

```fsharp
ISADotNet.XLSX.AssayFile.Assay.toFile outP assay
```

Assay file io

---

.github/workflows/build-test.yml
ISADotNet.sln
src/ISADotNet.Validation/ISADotNet.Validation.fsproj
src/ISADotNet.Validation/JsonSchemaValidation.fs
src/ISADotNet.Validation/ValidationResult.fs
tests/ISADotNet.Tests/ISADotNet.Tests.fsproj
tests/ISADotNet.Tests/ISADotNet.Validation/JSchemaValidationTests.fs
tests/ISADotNet.Tests/ISADotNet.Validation/TestFiles/PPVAdditionalField.json
tests/ISADotNet.Tests/ISADotNet.Validation/TestFiles/PPVBroken.json
tests/ISADotNet.Tests/ISADotNet.Validation/TestFiles/PPVOntology.json
tests/ISADotNet.Tests/ISADotNet.Validation/TestFiles/PPVUnit.json
tests/ISADotNet.Tests/ISADotNet.Validation/TestFiles/PPVUriWrong.json
tests/ISADotNet.Tests/ISADotNet.Validation/TestFiles/ProcessAdditionalField.json
tests/ISADotNet.Tests/ISADotNet.Validation/TestFiles/ProcessBroken.json
tests/ISADotNet.Tests/ISADotNet.Validation/TestFiles/ProcessDate.json
tests/ISADotNet.Tests/ISADotNet.Validation/TestFiles/ProcessDateTime.json
tests/ISADotNet.Tests/ISADotNet.Validation/TestFiles/ProcessDateWrong.json
tests/ISADotNet.Tests/ISADotnet/ISAJsonTests.fs
tests/ISADotNet.Tests/ISADotnet/TestFiles/AssayTestFile.json
tests/ISADotNet.Tests/ISADotnet/TestFiles/InvestigationTestFile.json
tests/ISADotNet.Tests/JsonSchemaValidation.fs
tests/ISADotNet.Tests/Main.fs

Edit 29.11.22:
- Created a new project `ISADotNet.Validation`
- Added functions for validating ISA Json against json schema
- Added tests for validation functions
- Added and fixed tests for ISA Json output
- Update dotnet version in cli to 6.x.x

Add Tests for Json Schema Validation

---

src/ISADotNet.XLSX/InvestigationFile/Publication.fs
src/ISADotNet/DataModel/Material.fs
src/ISADotNet/DataModel/Publication.fs
src/ISADotNet/JsonExtensions.fs
tests/ISADotNet.Tests/ISADotnet/ISAJsonTests.fs

- Added a comprehensive json schema test:
Full investigation with every field filled out
- Found two type errors, where the datamodel did not match the json schema:
- `Publication` does not have the field `@id`
- `Material` field `DerivesFrom` had the wrong type

Comprehensive json schema test

---

src/ISADotNet.Viz/DAG.fs
src/ISADotNet.XLSX/AssayFile/Assay.fs
src/ISADotNet.XLSX/AssayFile/MetaData.fs
src/ISADotNet.XLSX/StudyFile/MetaData.fs
src/ISADotNet.XLSX/StudyFile/Study.fs
src/ISADotNet/API/Material.fs
src/ISADotNet/API/Process.fs

- fix #51
- fix #71 
- fix https://github.com/nfdi4plants/arcCommander/issues/150
- add unit retrieval functions to API

Small fixes and changes

---

ARCtrl.sln
build.cmd
src/ARCtrl/ARCtrl.fs
src/ISA/ISA/ARCtrl.ISA.fsproj
src/ISA/ISA/ArcTypes/ArcInvestigation.fs
src/ISA/ISA/ArcTypes/CompositeCell.fs
src/ISA/ISA/JsonTypes/AnnotationValue.fs
tests/ISA/ISA.Tests/ArcInvestigation.Tests.fs
tests/ISA/ISA.Tests/CompositeCell.Tests.fs

Added tests and fixed issues with mutability on ARCtrl properties ✨

Add FindAssay with tests :sparkles:

---

src/ARCtrl/ARCtrl.fs
src/ISA/ISA/ArcTypes/ArcAssay.fs
src/ISA/ISA/ArcTypes/ArcStudy.fs
src/ISA/ISA/ArcTypes/ArcTables.fs
tests/ARCtrl/ARCtrl.Tests.fs
tests/ARCtrl/ARCtrl.Tests.fsproj
tests/ARCtrl/TestObjects/ISAContracts.fs
tests/ISA/ISA.Spreadsheet.Tests/ISA.Spreadsheet.Tests.fsproj
tests/ISA/ISA.Spreadsheet.Tests/TestObjects/Assay.fs
tests/ISA/ISA.Spreadsheet.Tests/TestObjects/InvestigationFile.fs
tests/ISA/ISA.Spreadsheet.Tests/TestObjects/Study.fs

Now study information from study file and investigation file is merged.
Fixes #160 
Will be necessary even after #167 because of existing arcs.
Added a big test for "SetISAFromContracts"

Hotfix isa from read contracts

---

src/ISA/ISA.Spreadsheet/InvestigationFile/Assays.fs
src/ISA/ISA/ArcTypes/ArcAssay.fs
tests/ISA/ISA.Tests/ArcAssay.Tests.fs
tests/ISA/ISA.Tests/ArcInvestigation.Tests.fs
tests/ISA/ISA.Tests/ArcJsonConversionTests.fs
tests/ISA/ISA.Tests/ArcStudy.Tests.fs

And add helper functions to parse to and from string representation in isa-json
closes #162

Make TechnologyPlatform an ontology term

---

RELEASE_NOTES.md
src/ISA/ISA/ArcTypes/ArcTable.fs
src/ISA/ISA/ArcTypes/ArcTableAux.fs
tests/ISA/ISA.Tests/ArcJsonConversionTests.fs

Empty Tables are now correctly converted to and from processlist
fix #193

Developer templates

---

ARCtrl.sln
package.json
src/ISA/ISA/ArcTypes/ArcTable.fs
src/ISA/ISA/ArcTypes/CompositeCell.fs
src/ISA/ISA/ArcTypes/CompositeHeader.fs
tests/ISA/ISA.Tests/ArcTable.Tests.fs
tests/ISA/ISA.Tests/CompositeCell.Tests.fs
tests/ISA/ISA.Tests/CompositeHeader.Tests.fs
tests/JavaScript/ISA.CompositeHeader.js
tests/TestingUtils/Library.fs

- closes #198 
- closes #190 
- closes #197

Solve Issues

---

ARCtrl.sln
src/ISA/ISA/ArcTypes/CompositeCell.fs
src/ISA/ISA/ArcTypes/CompositeHeader.fs
tests/JavaScript/ISA.CompositeCell.js
tests/JavaScript/ISA.CompositeHeader.js

Add js unioncase helpers and tests

---

src/ARCtrl/ARC.fs
tests/ARCtrl/ARCtrl.Tests.fs

Fix read in missing study

---

src/ARCtrl/Templates/Template.Json.fs
src/ISA/ISA.Json/ARCtrl.ISA.Json.fsproj
src/ISA/ISA.Json/ArcTypes/ArcAssay.fs
src/ISA/ISA.Json/ArcTypes/ArcInvestigation.fs
src/ISA/ISA.Json/ArcTypes/ArcStudy.fs
src/ISA/ISA.Json/ArcTypes/ArcTable.fs
src/ISA/ISA.Json/ArcTypes/CompositeCell.fs
src/ISA/ISA.Json/ArcTypes/CompositeHeader.fs
src/ISA/ISA.Json/ArcTypes/IOType.fs
src/ISA/ISA.Json/Assay.fs
src/ISA/ISA.Json/Investigation.fs
src/ISA/ISA.Json/Study.fs
src/ISA/ISA/ArcTypes/ArcTypes.fs
tests/ARCtrl/Template.Tests.fs
tests/ISA/ISA.Json.Tests/ArcTypes.Tests.fs
tests/ISA/ISA.Json.Tests/ISA.Json.Tests.fsproj
tests/ISA/ISA.Json.Tests/Main.fs
tests/JavaScript/Template.Web.js

- Add modules with encoders, decoders.
- Add AutoOpen type extensions.
- NOT breaking previous api syntax.
- moving ArcAssay, ArcStudy and ArcInvestigation functions to new files.
- Adding tests ✅

Add full conversions for ArcTypes to and from JSON

---

ARCtrl.sln
Speedtest/LargeStudy.fs
Speedtest/Program.fs
Speedtest/Speedtest.fsproj
src/ISA/ISA.Json/Ontology.fs
src/ISA/ISA.Spreadsheet/AnnotationTable/ArcTable.fs
src/ISA/ISA.Spreadsheet/ArcStudy.fs
src/ISA/ISA/ArcTypes/ArcTable.fs
src/ISA/ISA/ArcTypes/ArcTableAux.fs
src/ISA/ISA/ArcTypes/ArcTypes.fs
src/ISA/ISA/ArcTypes/CompositeCell.fs
src/ISA/ISA/Helper.fs
src/ISA/ISA/JsonTypes/AnnotationValue.fs
src/ISA/ISA/JsonTypes/Component.fs
src/ISA/ISA/JsonTypes/MaterialAttribute.fs
src/ISA/ISA/JsonTypes/OntologyAnnotation.fs
src/ISA/ISA/JsonTypes/ProtocolParameter.fs
src/ISA/ISA/JsonTypes/Value.fs
tests/ISA/ISA.Json.Tests/Json.Tests.fs
tests/ISA/ISA.Spreadsheet.Tests/Performance.Tests.fs

Create, write and read study is now 12x faster. Ontology Annotations now have flat string as `Annotation Value`

Speed boost for ArcTable creation and xlsx parsing

---

README.md
RELEASE_NOTES.md
build/release_package.json
src/ISA/ISA/ArcTypes/ArcTable.fs
tests/ISA/ISA.Tests/ArcTable.Tests.fs

Give option to give index where to join table.
✅  Added tests (3)

Extend ArcTable.Join logic 

---

src/ISA/ISA.Spreadsheet/AnnotationTable/ArcTable.fs
tests/ISA/ISA.Spreadsheet.Tests/ArcTableTests.fs

Test and fix empty table io

---

src/ISA/ISA.Spreadsheet/AnnotationTable/ArcTable.fs
src/ISA/ISA.Spreadsheet/ArcAssay.fs
src/ISA/ISA.Spreadsheet/ArcStudy.fs

Add some additional information to failing spreadsheet parsers

---

src/Core/Table/ArcTables.fs
tests/Core/ArcAssay.Tests.fs
tests/Core/ArcTables.Tests.fs

Make ArcTables construction fail for duplicate table names

---

src/ARCtrl/ARC.fs
src/Contract/Contract.fs
src/Core/ArcTypes.fs
tests/ARCtrl/ARCtrl.Tests.fs

Add rename contracts, assay and study rename logic

---

src/Core/Table/ArcTable.fs
src/Core/Table/ArcTableAux.fs
tests/Core/ArcTable.Tests.fs

Add column move function to ArcTable

---

src/Core/Helper/Regex.fs
tests/Core/Regex.Tests.fs

Make ArcTable header parsing patterns less strict

---

src/Json/Assay.fs
src/Json/Comment.fs
src/Json/Investigation.fs
src/Json/OntologyAnnotation.fs
src/Json/OntologySourceReference.fs
src/Json/Person.fs
src/Json/Process/Component.fs
src/Json/Process/Data.fs
src/Json/Process/DataFile.fs
src/Json/Process/Factor.fs
src/Json/Process/FactorValue.fs
src/Json/Process/Material.fs
src/Json/Process/MaterialAttribute.fs
src/Json/Process/MaterialAttributeValue.fs
src/Json/Process/MaterialType.fs
src/Json/Process/Process.fs
src/Json/Process/ProcessInput.fs
src/Json/Process/ProcessOutput.fs
src/Json/Process/ProcessParameterValue.fs
src/Json/Process/Protocol.fs
src/Json/Process/ProtocolParameter.fs
src/Json/Process/Sample.fs
src/Json/Process/Source.fs
src/Json/Publication.fs
src/Json/Study.fs
src/Json/Table/Templates.fs

Add toJsonString extensions members

---

src/ARCtrl/ARC.fs
src/Core/ArcTypes.fs
src/Core/Table/CompositeColumn.fs
src/Core/Table/CompositeHeader.fs
src/Spreadsheet/AnnotationTable/ArcTable.fs
src/Spreadsheet/ArcAssay.fs
src/Spreadsheet/ArcInvestigation.fs
src/Spreadsheet/ArcStudy.fs
src/Spreadsheet/Template.fs
tests/Core/ArcAssay.Tests.fs
tests/Core/ArcStudy.Tests.fs
tests/Core/CompositeCell.Tests.fs
tests/Core/CompositeHeader.Tests.fs
tests/Core/Fable.Tests.fs
tests/Spreadsheet/ArcTableTests.fs
tests/TestingUtils/TestObjects.Spreadsheet/Spreadsheet.Study.fs

closes #329 
closes #344
closes #414 
closes #415 
closes #416

Various fixes and small additions

---

src/FileSystem/Path.fs
tests/ARCtrl/ARCtrl.Tests.fs

Fix single dot in paths being interpreted as folder

---

src/Core/Conversion.fs
tests/Core/ArcAssay.Tests.fs

fixes https://github.com/nfdi4plants/Swate/issues/571

Fix technologyPlatform not handling parentheses

---

src/Json/Assay.fs
src/Json/Investigation.fs
src/Json/Study.fs
src/Json/context/rocrate/isa_investigation_context.fs
src/Json/context/rocrate/isa_study_context.fs
src/Json/context/rocrate/rocrate_context.fs
tests/Json/Investigation.Tests.fs
tests/TestingUtils/TestObjects.Json/Study.fs

This PR fixes several issues with the RO-Crate export, see https://github.com/nfdi4plants/ARCtrl/issues/472, https://github.com/nfdi4plants/ARCtrl/issues/473, https://github.com/nfdi4plants/ARCtrl/issues/484, https://github.com/nfdi4plants/ARCtrl/issues/485 and https://github.com/nfdi4plants/ARCtrl/issues/486.

RO-Crate Fixes

---

Directory.Packages.props
tests/ARCtrl/ARCtrl.Tests.fsproj
tests/All/All.Tests.fsproj
tests/Contract/ARCtrl.Contract.Tests.fsproj
tests/Core/ARCtrl.Core.Tests.fsproj
tests/FileSystem/ARCtrl.FileSystem.Tests.fsproj
tests/ROCrate/ARCtrl.ROCrate.Tests.fsproj
tests/Speedtest/Speedtest.fsproj
tests/Spreadsheet/ARCtrl.Spreadsheet.Tests.fsproj
tests/TestingUtils/TestObjects.Spreadsheet/Spreadsheet.ArcTable.fs
tests/TestingUtils/TestObjects.Spreadsheet/Spreadsheet.DataMap.fs
tests/TestingUtils/TestingUtils.fsproj
tests/ValidationPackages/ARCtrl.ValidationPackages.Tests.fsproj
tests/Yaml/ARCtrl.Yaml.Tests.fsproj

Update Fsspreadsheet and Thoth.Json dependencies
