nfdi4plants/ARCtrl

- src/ISADotnet/JsonIO/AssayCommonAPI.fs
When writing files to `rowMajorAssay` files, the order of `parameters`, `factors` and `characteristics` is lost. This commit fixes this.
> Fix rowMajorAssay to maintain value order

- src/ISADotNet.Viz/DAG.fs
- src/ISADotNet.XLSX/AssayFile/AnnotationColumn.fs
- src/ISADotNet.XLSX/AssayFile/Assay.fs
- src/ISADotNet.XLSX/ISADotNet.XLSX.fsproj
- src/ISADotNet.XLSX/InvestigationFile/Investigation.fs
- src/ISADotNet.XLSX/InvestigationFile/SparseTable.fs
- src/ISADotNet.XLSX/StudyFile/MetaData.fs
- src/ISADotNet.XLSX/StudyFile/Study.fs
- src/ISADotnet/API/Process.fs
- src/ISADotnet/DataModel/Factor.fs
- src/ISADotnet/DataModel/Material.fs
- src/ISADotnet/DataModel/Ontology.fs
- src/ISADotnet/DataModel/Process.fs
- src/ISADotnet/DataModel/Protocol.fs
- tests/ISADotNet.Tests/ISADotNet.Tests.fsproj
- tests/ISADotNet.Tests/ISADotNet.XLSX/AssayFileTests.fs
- tests/ISADotNet.Tests/ISADotNet.XLSX/RegexPattern.fs
- tests/ISADotNet.Tests/Main.fs
Removed some failing cases of header parsing (e.g. when there were brackets inside the name). Examples for these new rules are seen below:
`#` are now also included in the name together with potential numberings. Explanation see next section.
`ISADotNet` should follow more closely the `ISATab` specification and not impose any unncessary additional assumptions when simply parsing assay files. Therefore from now on ISADotNet will move towards interpreting headers with `Swate` style numbering (e.g. `Parameter [temperature unit#2]`) oblivious to these numberings. 
Members incoporating these numbering rules (e.g. `Factor.GetNameAsStringWithNumber`) are now marked as `deprecated` and will be omitted in future releases.
Failing xlsx readers will now be more verbose about why they are failing
- …
> Bugfixes and minor improvements

- src/ISADotNet/JsonExtensions.fs
- tests/ISADotNet.Tests/ISADotnet/JsonExtensionsTests.fs
Json AnyOf Deserializer returned erroneous results and failed sometimes when encountering escaped characters. This is now fixed and tests were added.
Additionally made the deserializers more verbose about why they fail.
fixes #47
> Json Deserialization Fix

- src/ISADotNet.XLSX/InvestigationFile/Investigation.fs
- src/ISADotNet/JsonIO/Investigation.fs
- tests/ISADotNet.Tests/ISADotnet/ISAJsonTests.fs
Until now, when an isa investigation json string was read by the json parser, `null` was set as the value for the `Remarks` field. This would lead to errors when trying to parse this object to an xlsx afterwards. 
Now fixed and a test was added.
> Small fix to investigation json parser

- src/ARCtrl/ARCtrl.fs
- src/ARCtrl/ARCtrl.fsproj
- src/ARCtrl/FileSystemTree.fs
- src/ARCtrl/Path.fs
- src/CWL/CWL.fsproj
- src/CWL/Path.fs
- src/Contract/Contract.fs
- src/FileSystem/FileSystem.fs
- src/FileSystem/FileSystemTree.fs
- tests/ARCtrl/ARCtrl.Tests.fs
- test getWriteContracts
- use literals in getWriteContracts
- make toplevel fields mutable
closes #148 
closes #149
> Improve ARCtrl write

- src/ISA/ISA.Json/Ontology.fs
- src/ISA/ISA.Spreadsheet/CompositeHeader.fs
- src/ISA/ISA/ArcTypes/CompositeCell.fs
- src/ISA/ISA/ArcTypes/CompositeHeader.fs
- src/ISA/ISA/JsonTypes/Component.fs
- src/ISA/ISA/JsonTypes/OntologyAnnotation.fs
- src/ISA/ISA/Regex.fs
- tests/ISA/ISA.Json.Tests/Json.Tests.fs
- tests/ISA/ISA.Tests/ArcTable.Tests.fs
- tests/ISA/ISA.Tests/Regex.Tests.fs
#161 
- `LocalID` field removed
- Instead there is an `IDInfo` member with both the `IDSpace` and the `LocalID`
Maybe rename to `TANInfo`? @Freymaurer
> Rework ontologyannotation localID field

- src/ISA/ISA/ArcTypes/ArcTable.fs
- src/ISA/ISA/ArcTypes/CompositeRow.fs
- tests/ISA/ISA.Tests/ArcJsonConversionTests.fs
Parsing between ArcTables and Protocols lead to breaking changes when writing and reading an ARC. 
This is because the name of the ArcTables was not included into the protocol, leading to empty protocols in the study section of the investigation file when writing. These would then be read to nameless ArcTables, leasing to breaks. 
- Fixed this broken behaviour 
- added another safetynet, namely using `Missing identifiers` when reading nameless protocols
- added tests
> Hotfix protocol handling

- src/ARCtrl/ARCtrl.fs
- src/FileSystem/FileSystem.fs
- src/FileSystem/FileSystemTree.fs
- tests/ARCtrl/ARCtrl.Tests.fs
`ARC.GetWriteContracts` previously failed, when two studies contained the same assay. Fixed this misbehaviour and added tests.
> Hotfix GetWriteContracts

- src/ARCtrl/ARCtrl.fs
- src/FileSystem/FileSystemTree.fs
- tests/ARCtrl/ARCtrl.Tests.fs
- tests/FileSystem/FileSystemTree.Tests.fs
closes #188:
- Add FileSystemTree.FilterFolders
- FileSystemTree.FilterFiles now only filters files (returns empty folders instead of removing them)
- fix some static member bindings
- Add tests for FilterFolders
- Tests now test both instance and static methods
closes #187:
- Add `GetRegisteredPayload` and `GetAdditionalPayload`
- Add tests
> FileSystemTree additions and Payload detection

- src/ARCtrl/ARCtrl.fs
- src/ARCtrl/ARCtrl.fsproj
- src/ARCtrl/Contracts/Contracts.Git.fs
- src/Contract/Contract.fs
- src/FileSystem/ARCtrl.FileSystem.fsproj
- src/FileSystem/DefaultGitignore.fs
- tests/ARCtrl/ARCtrl.Contracts.Tests.fs
- add git init
- add git clone
- add .gitignore
https://github.com/nfdi4plants/ARCtrl/issues/196
(Last rebase caused bigger issues in initial branch)
> [Reworked #202] Add simple git functions to test contract behaviour

- RELEASE_NOTES.md
- build/BasicTasks.fs
- build/Build.fs
- build/Build.fsproj
- build/PackageTasks.fs
- build/ProjectInfo.fs
- build/ReleaseNotesTasks.fs
- build/ReleaseTasks.fs
- build/release_package.json
- package-lock.json
- package.json
- tests/ARCtrl/WebRequest.Tests.fs
Add build targets for automatic packing and publishing of npm package:
New package: https://www.npmjs.com/package/@nfdi4plants/arctrl/v/1.0.0-alpha7?activeTab=readme
Newly added:
```cli
.\build.cmd packJS
.\build.cmd packJSPrerelease
.\build.cmd publishNPM
.\build.cmd publishNPMPrerelease
```
-------
```cli
.\build.cmd release
.\build.cmd prerelease
```
now do nuget, npm and github release
> Add Npm release as build target

- build/GenerateIndexJs.fs
- src/ARCtrl/ARCtrl.fsproj
- src/ARCtrl/Templates/Template.Json.fs
- src/ARCtrl/Templates/Template.Web.fs
- src/ARCtrl/Templates/Templates.fs
- src/ISA/ISA.Spreadsheet/AnnotationTable/ArcTable.fs
- src/ISA/ISA/ArcTypes/ArcTable.fs
- src/ISA/ISA/ArcTypes/ArcTableAux.fs
- src/ISA/ISA/ArcTypes/ArcTypes.fs
- src/ISA/ISA/ArcTypes/CompositeColumn.fs
- src/ISA/ISA/ArcTypes/CompositeHeader.fs
- src/ISA/ISA/Helper.fs
- tests/ARCtrl/Template.Tests.fs
- tests/ISA/ISA.Tests/ArcAssay.Tests.fs
- tests/ISA/ISA.Tests/ArcInvestigation.Tests.fs
- tests/ISA/ISA.Tests/ArcStudy.Tests.fs
- tests/ISA/ISA.Tests/ArcTable.Tests.fs
- tests/ISA/ISA.Tests/CompositeColumn.Tests.fs
- tests/ISA/ISA.Tests/CompositeHeader.Tests.fs
- tests/JavaScript/Template.Web.js
Will come with some utility functions:
- `import { Templates } from 'arctrl'` (please verify import from index.js works correctly), has functions to filter arrays of templates.
- `Templates.getDistinctTags()`, `Templates.getDistinctEndpointRepositories()`, `getDistinctOntologyAnnotations()`
- `Templates.filterByTags(tagArray)`, also exists for EndpointRepositories and OntologyAnnotations. Can be used with optional boolean input to toggle between OR and AND search. Default is false, is OR.
```js
const templates = [create_TestTemplate()];
const queryTags = [OntologyAnnotation.fromString("DNA"), OntologyAnnotation.fromString("RNA")];
Templates.filterByOntologyAnnotation(queryTags, true)(templates); //example for AND search
```
- `CompositeHeader` and `IOType` both have …
> Developer swatelogic

- src/ISA/ISA/ArcTypes/ArcTable.fs
- src/ISA/ISA/ArcTypes/ArcTables.fs
- src/ISA/ISA/ArcTypes/ArcTypes.fs
- src/ISA/ISA/ArcTypes/CompositeHeader.fs
- tests/ISA/ISA.Tests/ArcInvestigation.Tests.fs
> Add function for updating IO types against each other in ARC

- src/ISA/ISA.Spreadsheet/ArcInvestigation.fs
- tests/ISA/ISA.Json.Tests/Json.Tests.fs
- tests/ISA/ISA.Spreadsheet.Tests/InvestigationFileTests.fs
`ArcInvestigation.toFsWorkbook` now only writes registered studies to investigation file.
closes #229
> ArcInvestigation writer fix

- .github/workflows/build-test.yml
- README.md
- docs/ARC.md
- docs/Contracts.md
- docs/GettingStarted.md
- docs/scripts_fsharp/ARC.fsx
- docs/scripts_fsharp/Contracts.fsx
- docs/scripts_js/ARC.js
- docs/scripts_js/Contracts.js
- docs/scripts_js/package-lock.json
- docs/scripts_js/package.json
- package-lock.json
- package.json
- src/ARCtrl/ARC.fs
- src/ARCtrl/Templates/Template.Json.fs
- src/ARCtrl/Templates/Template.Spreadsheet.fs
- src/Contract/Contract.fs
- src/Contract/README.md
- src/ISA/ISA.Spreadsheet/ArcAssay.fs
- src/ISA/ISA/ArcTypes/ArcTables.fs
- src/ISA/ISA/ArcTypes/ArcTypes.fs
- tests/ARCtrl/ARCtrl.Tests.fs
- tests/ISA/ISA.Spreadsheet.Tests/AssayFileTests.fs
- tests/ISA/ISA.Tests/ArcJsonConversionTests.fs
- tests/ISA/ISA.Tests/ArcStudy.Tests.fs
- tests/ISA/ISA.Tests/ArcTables.Tests.fs
- tests/TestingUtils/TestObjects.Contract/ISA.fs
Starting to write developer docs. Until Fable allows keeping comments, auto generated source code docs do not seem like a valid option.
@JonasLukasczyk please have a look at the js code implementation `/docs/scripts_js/ARC.js` and please just sent me all of your ARCtrl code implementations.
@HLWeil tell me if you are okay with the structur, file placement, etc.
closes #223 
closes #231 
closes #233 
closes #234 
closes #232 
closes #114
> [WIP] Developer docs

- README.md
- docs/scripts_js/Tables.js
- docs/scripts_js/package-lock.json
- docs/scripts_js/package.json
- Added a small example script for creating and writing an assay with a table
- Made README.md shield.io badges directly link to packages
> Miniscule table documentation script in javascript

- src/ISA/ISA/ArcTypes/ArcTypes.fs
- src/ISA/ISA/Helper.fs
- tests/ISA/ISA.Tests/ArcInvestigation.Tests.fs
- tests/ISA/ISA.Tests/ArcStudy.Tests.fs
- tests/ISA/ISA.Tests/DataModel.Tests.fs
New Keywords: 
- `Vacant` = RegisteredButNotExisting
- `Unregistered` = ExistingButNotRegistered
Changes:
- `RegisteredXCount` now only returns the count of those `X` that are registered AND existing, like `RegisteredXs`. 
- `RegisteredXIdentifierCount` returns that what `RegisteredXCount` used to return
Tests
> Registration sensitive arc type getter functions

- RELEASE_NOTES.md
- build/release_package.json
- src/ISA/ISA.Spreadsheet/ARCtrl.ISA.Spreadsheet.fsproj
- src/ISA/ISA.Spreadsheet/Metadata/SparseTable.fs
- src/ISA/ISA/ArcTypes/ArcTable.fs
- src/ISA/ISA/ArcTypes/ArcTableAux.fs
- tests/ISA/ISA.Spreadsheet.Tests/Performance.Tests.fs
- tests/ISA/ISA.Tests/ArcTable.Tests.fs
- tests/ISA/ISA.Tests/Library.fs
- tests/Speedtest/AddRows.fs
- tests/Speedtest/FillMissing.fs
- tests/Speedtest/ManyStudies.fs
- tests/Speedtest/Program.fs
- tests/Speedtest/Speedtest.fsproj
- tests/TestingUtils/Library.fs
Writing investigation file with many rows (e.g. 5000 studies) was very slow with quadratic time. Fixed by using the improved `rowWithRange` function form FsSpreadsheet, which skips checking all rows on every call.
- Improved fillMissing by roughly a factor of 8
- Improved addRows, which had a quadratic time dependency because of using `getRowCount` in every step
> Several performance increases

- src/ARCtrl/ARC.fs
- src/ARCtrl/Contracts/Contracts.ArcTypes.fs
- src/ISA/ISA/ArcTypes/ArcTable.fs
- src/ISA/ISA/ArcTypes/ArcTableAux.fs
- src/ISA/ISA/ArcTypes/ArcTypes.fs
- tests/ARCtrl/ARCtrl.Tests.fs
- tests/ISA/ISA.Tests/ArcTable.Tests.fs
Introduced a 
```fsharp
arc.GetUpdateContracts()
```
member, which only returns `Update` contracts for the entities that have been changed. If an entity is added, the appropriate `Create` contracts are returned. Accordingly, if the ARC is initilialized in memory and not written yet, all `Create` contracts are returned.
The check, whether an entity has changed or not is done by keeping a `StaticHash` field in `Assays`, `Studies` and `Investigations`. These are set either when using `SetISAFromContracts` (Read) or when using `GetWriteContracts/GetUpdateContracts` (Write).
closes #309 
closes #131
> Implement Update logic

- src/ISA/ISA.Json/ARCtrl.ISA.Json.fsproj
- src/ISA/ISA.Json/ArcTypes/ArcAssay.fs
- src/ISA/ISA.Json/ArcTypes/ArcStudy.fs
- src/ISA/ISA.Json/ArcTypes/ArcTable.fs
- src/ISA/ISA.Json/ArcTypes/CellTable.fs
- src/ISA/ISA.Json/ArcTypes/CompositeCell.fs
- src/ISA/ISA.Json/ArcTypes/OATable.fs
- src/ISA/ISA.Json/Ontology.fs
- src/ISA/ISA.Json/StringTable.fs
- src/ISA/ISA/ArcTypes/ArcTable.fs
- tests/ISA/ISA.Json.Tests/ArcTypes.Tests.fs
Added compressed json encoders to reduce size of output json. These make use of Cell-, OntologyAnnotation- and Stringtables to deduplicate information.
In DotNet it's not only much smaller, but also much faster. Unfortunately, this is not the case for JS. Therefore the performance test is pending in Fable.
> Json compression

- ARCtrl.sln
- build/GenerateIndexJs.fs
- build/GenerateIndexPy.fs
- src/ARCtrl/ARCtrl.fsproj
- src/ARCtrl/Json.fs
- src/ARCtrl/Xlsx.fs
- src/Core/OntologyAnnotation.fs
- src/Json/ARCtrl.Json.fsproj
- tests/JavaScript/JsonController.js
- tests/JavaScript/XlsxController.js
- tests/Json/Person.Tests.fs
- tests/Json/Publication.Tests.fs
- tests/Python/test_JsonController.py
- tests/Python/test_XlsxController.py
- tests/Python/test_index.py
- I prove JsonController logic
- Add XlsxController
- Add Native tests
> XlsxController

- README.md
- RELEASE_NOTES.md
- build/BasicTasks.fs
- build/Build.fs
- build/Helpers.fs
- build/PackageTasks.fs
- build/ProjectInfo.fs
- build/ReleaseTasks.fs
- build/release_package.json
- pyproject.toml
- src/ARCtrl/ARCtrl.fsproj
- src/CWL/ARCtrl.CWL.fsproj
- src/Contract/ARCtrl.Contract.fsproj
- src/Core/ARCtrl.Core.fsproj
- src/FileSystem/ARCtrl.FileSystem.fsproj
- src/Json/ARCtrl.Json.fsproj
- src/Spreadsheet/ARCtrl.Spreadsheet.fsproj
- Include python prerelease build target
- Change prerelease input mask: Now two prompts asking for short code (a/b/rc) and Number
> Update prerelease mechanism

- src/ARCtrl/ARC.fs
- src/Contract/Git.fs
- src/FileSystem/ARCtrl.FileSystem.fsproj
- src/FileSystem/DefaultGitattributes.fs
- tests/ARCtrl/ARCtrl.Contracts.Tests.fs
#354 
I've left the dto empty as asked for in the issue, but maybe we could add a default rule like `**/dataset/**`. Let me know what you think, @Freymaurer @JonasLukasczyk
> Add gitattributes contract to gitinitcontracts

- src/ARCtrl/ARCtrl.fsproj
- src/Contract/ARCtrl.Contract.fsproj
- src/Core/ARCtrl.Core.fsproj
- src/FileSystem/ARCtrl.FileSystem.fsproj
- src/Json/ARCtrl.Json.fsproj
- src/Spreadsheet/ARCtrl.Spreadsheet.fsproj
> Fix missing fable includes #369

- src/ARCtrl/Template.Web.fs
- src/Json/Table/Templates.fs
- tests/ARCtrl/Template.Tests.fs
- tests/Json/Template.Tests.fs
Both json encoder and json decoder now expect a Template Array.
closes #375
Updated the default URI to new Swate-templates release v2.0.0
closes #374
> Update templates json parsing

- src/Core/Table/ArcTableAux.fs
- src/Core/Table/CompositeCell.fs
- src/Json/Table/CellTable.fs
- tests/Core/ArcTable.Tests.fs
- tests/Json/ArcTable.Tests.fs
ArcTable.FillMissingCells and Json CompositeCell compressed decoder now Copy CompositeCell to avoid OntologyAnnotation mutability issues.
closes #378
> Increase robustness against OntologyAnnotation mutability issues

- src/Core/ARCtrl.Core.fsproj
- src/Core/Helper/Regex.fs
- src/Core/Helper/Url.fs
- src/Core/OntologyAnnotation.fs
- tests/Core/ARCtrl.Core.Tests.fsproj
- tests/Core/Main.fs
- tests/Core/OntologyAnnotation.Tests.fs
- tests/Core/UriHelper.Tests.fs
- tests/TestingUtils/TestObjects.Spreadsheet/Spreadsheet.ArcTable.fs
- tests/TestingUtils/TestObjects.Spreadsheet/Spreadsheet.Template.fs
URL generation does now not always produce PURLs, but different URLs depending on the Ontology namespace.
```
"DPBO", OntobeeDPBOParser
"MS", MSParser
"PO", POParser
"RO", ROParser
"ENVO", BioregistryParser
"CHEBI", BioregistryParser
"GO", BioregistryParser
"OBI", BioregistryParser
"PATO", BioregistryParser
"PECO", BioregistryParser
"TO", BioregistryParser
"UO", BioregistryParser
"EFO", BioregistryParser
"NCIT", BioregistryParser
"OMP", BioregistryParser
```
closes #368
> Rework Ontoly Term Uri generation

- src/Spreadsheet/AnnotationTable/ArcTable.fs
- src/Spreadsheet/AnnotationTable/CompositeCell.fs
- src/Spreadsheet/AnnotationTable/CompositeColumn.fs
- src/Spreadsheet/AnnotationTable/CompositeHeader.fs
- tests/Spreadsheet/ArcTableTests.fs
- tests/Spreadsheet/CompositeHeaderTests.fs
- tests/TestingUtils/TestObjects.Spreadsheet/Spreadsheet.ArcTable.fs
> Base spreadsheet parsers on string columns

- src/Core/Table/ArcTable.fs
- tests/Core/ArcTable.Tests.fs
AddColumnFill adds a new column with the given header and sets this cell for every row of this new column. The parameters are equivalent to addColumn. Two testCases have been implemented and two are still under construction. 
closes #399
> add addColumnFill member function with tests

- src/Core/Table/ArcTable.fs
- src/Core/Table/CompositeCell.fs
- src/Core/Table/CompositeColumn.fs
- tests/Core/ArcTable.Tests.fs
> Add  ArcTable cell accession and manipulation functions

- src/Core/Table/ArcTable.fs
- tests/Core/ArcTable.Tests.fs
Changes in ArcTable.fs and ArcTable.Tests.fs adding the functionality discussed in Issue #440
> add tryGetColumnByHeaderBy member and static + tests

- src/ARCtrl/WebRequest/WebRequest.Node.fs
- src/Json/ARC.fs
- src/Json/ARCtrl.Json.fsproj
- src/Json/Assay.fs
- src/Json/Comment.fs
- src/Json/Data.fs
- src/Json/DataMap/DataContext.fs
- src/Json/Encode.fs
- src/Json/IDTable.fs
- src/Json/Investigation.fs
- src/Json/OntologyAnnotation.fs
- src/Json/OntologySourceReference.fs
- src/Json/Person.fs
- src/Json/Process/Component.fs
- src/Json/Process/FactorValue.fs
- src/Json/Process/Material.fs
- src/Json/Process/MaterialAttributeValue.fs
- src/Json/Process/Process.fs
- src/Json/Process/ProcessParameterValue.fs
- src/Json/Process/Protocol.fs
- src/Json/Process/Sample.fs
- src/Json/Process/Source.fs
- src/Json/PropertyValue.fs
- src/Json/Publication.fs
- src/Json/Study.fs
- src/Json/Table/Compression.fs
- src/Json/Table/Templates.fs
- src/Spreadsheet/ARCtrl.Spreadsheet.fsproj
- use temporary FsSpreadsheet implementations for js and py
- update to thoth.json.core 0.4.0
> JsonIO rework

- src/ARCtrl/packages.lock.json
- src/Spreadsheet/ArcAssay.fs
- src/Spreadsheet/ArcInvestigation.fs
- src/Spreadsheet/ArcStudy.fs
- src/Spreadsheet/DataMap.fs
- src/Spreadsheet/Template.fs
- tests/Spreadsheet/AssayFileTests.fs
- tests/Spreadsheet/InvestigationFileTests.fs
- tests/Spreadsheet/StudyFileTests.fs
- tests/Spreadsheet/TemplateTests.fs
- tests/TestingUtils/TestObjects.Spreadsheet/Spreadsheet.Assay.fs
- tests/TestingUtils/TestObjects.Spreadsheet/Spreadsheet.InvestigationFile.fs
- tests/TestingUtils/TestObjects.Spreadsheet/Spreadsheet.Study.fs
- tests/TestingUtils/TestObjects.Spreadsheet/Spreadsheet.Template.fs
> Feature enable sequence based metadata creation

- src/Spreadsheet/Template.fs
> Enable check for metadata sheetname and is meta data sheet for arc template

- src/Core/OntologyAnnotation.fs
- tests/Core/OntologyAnnotation.Tests.fs
> Make OntologyAnnotation work with localID as TAN

- src/Core/ArcTypes.fs
- src/Core/Table/ArcTable.fs
- src/Core/Table/CompositeHeader.fs
- src/Core/Template.fs
- tests/Core/ArcTable.Tests.fs
- tests/Core/Template.Tests.fs
> Template copy and test+fix deepcopying of ArcTable

- src/Core/Helper/Identifier.fs
- src/Core/OntologyAnnotation.fs
- src/Spreadsheet/AnnotationTable/ArcTable.fs
- tests/Json/Process/ProcessParameterValue.fs
- tests/Spreadsheet/ArcTableTests.fs
- tests/Spreadsheet/CompositeHeaderTests.fs
Row count of Spreadsheet Table (including headers) is now increased to minimally 2, when writing. This way excel will not complain.
closes #462 
Also did a small adjusment, where read OntologyAnnotations will treat empty strings as None
> Fix for writing bodyless tables

- src/Json/Process/Material.fs
- src/Json/Process/ProcessInput.fs
- src/Json/Process/Sample.fs
- src/Json/Process/Source.fs
- src/Json/context/rocrate/isa_assay_context.fs
- tests/Json/Process/ProcessInput.Tests.fs
> fix additionalProperties being lost in RO-Crate write read

- src/Spreadsheet/ArcInvestigation.fs
- tests/Spreadsheet/InvestigationFileTests.fs
- tests/TestingUtils/TestObjects.Spreadsheet/Spreadsheet.InvestigationFile.fs
This PR
- changes the `fromRows` function in `ARCtrl.Spreadsheet.ArcInvestigation` module in such a way that it now checks for the presence of the Investigation identifier and fails if it is empty
- adds the respective unit test
- comments out unit tests `ReaderSuccessEmpty` and `WriterSuccessEmpty` since they don't make sense anymore
- fixes #519 
- has **NO** playground files added to the solution (thank God!) @HLWeil
> Check for Investigation identifier presence

- build/TestTasks.fs
- package-lock.json
- package.json
- src/ARCtrl/ContractIO/FileSystemHelper.fs
- src/ARCtrl/WebRequest/WebRequest.Node.fs
- src/FileSystem/Path.fs
- tests/WebBundling/README.md
- tests/WebBundling/index.html
- tests/WebBundling/main.ts
- tests/WebBundling/vite.config.js
- tsconfig.json
- vite.config.mts
When using ARCtrl in the browser with vite bundler you get error messages like such on bundling:
```bash
error during build:
node_modules/@nfdi4plants/arctrl/dist/ts/esm/ts/ContractIO/FileSystemHelper.js (3:15): "dirname" is not exported by "__vite-browser-external", imported by "node_modules/@nfdi4plants/arctrl/dist/ts/esm/ts/ContractIO/FileSystemHelper.js".
file: C:/Users/Kevin/Desktop/react-test/node_modules/@nfdi4plants/arctrl/dist/ts/esm/ts/ContractIO/FileSystemHelper.js:3:15
1: import { PromiseBuilder__Delay_62FBFDE1, PromiseBuilder__Run_212F1D4B } from "../fable_modules/Fable.Promise.3.2.0/Pr...
2: import { promise } from "../fable_modules/Fable.Promise.3.2.0/PromiseImpl.fs.js";
3: import { join, dirname } from "path";
^
4: import { …
```
> establish async dynamic import logic ✅

- .github/workflows/build-test.yml
- build/TestTasks.fs
- src/ARCtrl/ARC.fs
- src/ARCtrl/Conversion.fs
- src/ARCtrl/ROCrateIO.fs
- src/ARCtrl/__init__.py
- src/ARCtrl/index.ts
- src/FileSystem/FileSystemTree.fs
- tests/ARCtrl/ARCtrl.Tests.fs
- tests/ARCtrl/ROCrateConversion.Tests.fs
- tests/FileSystem/FileSystemTree.Tests.fs
- tests/TestingUtils/TestingUtils.fs
connected to https://github.com/nfdi4plants/arc-export/issues/54
In ARC Scaffold [Annotation Tables](https://github.com/nfdi4plants/ARC-specification/blob/release/ISA-XLSX.md#annotation-table-sheets), `Data` objects can be used as Inputs or Outputs. In the actual ARC Filesystem, these `Data` annotations can refer to three different entities:
- File
- File Fragment 
- Folder
All of these make sense and there is currently no intention to change this annotation in the ARC Scaffold. 
The problem arises, when mapping the `ARC Scaffold` metadata to `ARC RO-Crate` metadata json. The RO-Crate is meant to be used for various tasks and should be as semantically sound as possible. This is not the case at the moment, as the `Folder` objects in the Annotation Table are just mapped to `Files` in …
> More closely follow file system in RO-Crate metadata json
